### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [Soumya-Kushwaha/Intelligent-AI#1]

**Comment by RAAFTAR1591** [comment]
Hello, I am a new to contribution system. Can you assign this issure to me so that I can work on it? And, if possible can you give a brief description of what type of description readme file do you want?

**Comment by Soumya-Kushwaha** [comment]
Hey @RAAFTAR1591 
Assigned you. Go ahead.

The repo readme would contain basic info on AI.
And tell people that they can contribute their little basic projects, AI applications, documentations related to AI to this repo. Everything shall be welcome!

**Comment by RAAFTAR1591** [comment]
I updated the README.md. Please suggest if any changes are required.
